# Generated by Django 4.2.3 on 2023-07-24 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockaep', '0004_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='marca',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='stockaep.marca'),
        ),
    ]
