# Generated by Django 4.2.3 on 2023-07-24 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockaep', '0006_alter_hardware_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(default='S/D', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='S/D', max_length=100, unique=True)),
                ('marca', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stockaep.marca')),
            ],
        ),
        migrations.AddField(
            model_name='hardware',
            name='modelo',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='stockaep.modelo'),
        ),
    ]
