# Generated by Django 4.2.3 on 2023-07-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockaep', '0008_ubicacion_hardware_estado_hardware_nro_de_serie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='nro_de_serie',
            field=models.CharField(default='S/D', max_length=100),
        ),
    ]
