# Generated by Django 4.2.3 on 2023-07-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockaep', '0009_alter_hardware_nro_de_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='nombre',
            field=models.CharField(default='S/D', max_length=100),
        ),
    ]
