# Generated by Django 4.2.3 on 2023-07-26 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockaep', '0010_alter_modelo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockaep.marca'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockaep.modelo'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='nro_de_serie',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockaep.tipo'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockaep.ubicacion'),
        ),
    ]
