# Generated by Django 4.1.5 on 2023-08-21 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockaep', '0011_alter_hardware_marca_alter_hardware_modelo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Activo', 'Activo'), ('En uso', 'En uso'), ('Fuera de Servicio', 'Fuera de Servicio'), ('Scrap', 'Scrap'), ('Scrap', 'RMA')], max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='hardware',
            options={'ordering': ['tipo']},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='tipo',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='hardware',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockaep.estado'),
        ),
    ]
