# Generated by Django 4.0.2 on 2023-08-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockaep', '0014_notificacion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='estado',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
