# Generated by Django 4.0.2 on 2023-08-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockaep', '0015_notificacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='nro_de_serie',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
