# Generated by Django 4.0.2 on 2023-08-26 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockaep', '0016_notificacion_nro_de_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='hardware',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='stockaep.hardware'),
        ),
    ]
