# Generated by Django 4.0.2 on 2023-08-29 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockaep', '0017_alter_notificacion_hardware'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='hardware',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='stockaep.hardware'),
        ),
    ]
