# Generated by Django 4.0.2 on 2023-08-30 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockaep', '0021_alter_hardware_observaciones_asignacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='observaciones',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
