# Generated by Django 4.0.2 on 2023-09-01 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockaep', '0022_alter_hardware_observaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stockaep.hardware')),
            ],
        ),
    ]
