# Generated by Django 4.0.2 on 2023-09-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockaep', '0023_asignacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='nro_de_serie',
            field=models.CharField(default='???', max_length=100),
        ),
    ]
