# Generated by Django 4.0.2 on 2023-09-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockaep', '0024_alter_hardware_nro_de_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='nota',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='nro_ticket',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='nro_de_serie',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
