# Generated by Django 4.0.2 on 2023-09-17 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockaep', '0026_alter_asignacion_hardware'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='hardware',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockaep.hardware'),
        ),
    ]
