# Generated by Django 4.0.2 on 2023-09-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockaep', '0027_alter_asignacion_hardware'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='origen',
            field=models.CharField(choices=[('T4', 'T4'), ('CAU', 'CAU'), ('Yenny', 'Yenny')], default='CAU', max_length=10),
        ),
    ]
