# Generated by Django 4.0.2 on 2023-09-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockaep', '0028_hardware_origen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estado',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='modelo',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterField(
            model_name='estado',
            name='nombre',
            field=models.CharField(choices=[('Activo', 'Activo'), ('En uso', 'En uso'), ('Fuera de Servicio', 'Fuera de Servicio'), ('Scrap', 'Scrap'), ('RMA', 'RMA')], max_length=50),
        ),
    ]
