# Generated by Django 4.0.2 on 2023-09-18 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockaep', '0030_alter_modelo_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo',
            name='marca',
        ),
    ]
