# Generated by Django 4.0.2 on 2023-10-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockaep', '0031_remove_modelo_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='nota',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='estado',
            name='nombre',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('Activo', 'Activo'), ('En uso', 'En uso'), ('Fuera de Servicio', 'Fuera de Servicio'), ('Scrap', 'Scrap'), ('RMA', 'RMA')], max_length=50),
        ),
    ]
