# Generated by Django 4.2.3 on 2023-10-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockaep', '0032_hardware_nota_alter_estado_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
