# Generated by Django 4.2.3 on 2023-10-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockaep', '0033_alter_asignacion_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_creacion',
            field=models.DateField(),
        ),
    ]
