# Generated by Django 4.2.3 on 2023-10-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockaep', '0034_alter_asignacion_fecha_creacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacion',
            options={'ordering': ['fecha_creacion']},
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
